openapi: 3.0.1
info:
  title: TAO Core Internal API
  description: 'TAO Core Internal API'
  version: v1

paths:
  /tao/Translation/update:
    post:
      summary: Return a list of translations for a given translatable resource
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: The resource URI
                progress:
                  type: string
                  description: The progress URI
      responses:
        200:
          $ref: '#/components/responses/TranslateResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /tao/Translation/sync:
    post:
      summary: Sync resource with last translation updates
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: The resource URI
                languageUri:
                  type: string
                  description: The language URI
      responses:
        200:
          $ref: '#/components/responses/TranslateResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /tao/Translation/translations:
    get:
      summary: Return a list of translations for a given translatable resource
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: The RDF resource id
        - in: query
          name: languageUri
          required: false
          schema:
            type: string
          description: The RDF language URI
      responses:
        200:
          $ref: '#/components/responses/TranslationsResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /tao/Translation/translatable:
    get:
      summary: Return translatable resources
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: The RDF resource id
      responses:
        200:
          $ref: '#/components/responses/TranslatableResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /tao/Translation/status:
    get:
      summary: Return translatable status
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: The RDF resource id
      responses:
        200:
          $ref: '#/components/responses/TranslatableStatusResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /tao/Translation/translate:
    post:
      summary: translate a resources
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: The resource URI
                languageUri:
                  type: string
                  description: The language resource URI
      responses:
        200:
          $ref: '#/components/responses/TranslateResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /tao/Translation/delete:
    post:
      summary: delete translation
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: The resource URI
                languageUri:
                  type: string
                  description: The language resource URI
      responses:
        200:
          $ref: '#/components/responses/TranslateResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /tao/Languages/index:
    get:
      summary: Get a list of available languages in the TAO platform
      responses:
        200:
          $ref: '#/components/responses/LanguagesResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /tao/ResourceRelations:
    get:
      summary: Get the resource relations
      parameters:
        - in: query
          name: sourceId
          required: false
          schema:
            type: string
          description: The sourceId of the relation. In case of RDF id, this parameter must be urlencoded.
        - in: query
          name: classId
          required: false
          schema:
            type: string
          description: The classId will deterimine to make recursive search in order to find media that is .
        - in: query
          name: type
          required: false
          schema:
            type: string
          description: The type of resource to find relations with
      responses:
        200:
          $ref: '#/components/responses/ResourceRelationsResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
components:
  schemas:
    Translations:
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            resources:
              type: array
              items:
                properties:
                  originResourceUri:
                    type: string
                  resourceUri:
                    type: string
                  resourceLabel:
                    type: string
                  metadata:
                    type: object
                    properties:
                      key:
                        type: object
                        properties:
                          value:
                            type: string
                          literal:
                            type: string
    Translatable:
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            resources:
              type: array
              items:
                properties:
                  resourceUri:
                    type: string
                  resourceLabel:
                    type: string
                  metadata:
                    type: object
                    properties:
                      key:
                        type: object
                        properties:
                          value:
                            type: string
                          literal:
                            type: string
    TranslatableStatus:
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            resources:
              type: array
              items:
                properties:
                  uri:
                    type: string
                  type:
                    type: string
                  isReadyForTranslation:
                    type: boolean
                  isEmpty:
                    type: boolean
    Translated:
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            resourceUri:
              type: string
    ResourceRelationResource:
      description: 'A resource related to another resources'
      type: object
      properties:
        id:
          type: string
          example: 'http://www.tao.lu/tao.rdf#i5e89a2063326711164b1a816b433b1ec'
        type:
          type: string
          enum:
            - item
            - media
            - sharedStimulus
        data:
          description: specific payload according to type
          type: array
          items:
            type: object
          example:
            - label: 'My Item'
      required:
        - classId
    ResourceRelations:
      description: 'A relationship between two resources'
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            relations:
              type: array
              items:
                $ref: '#/components/schemas/ResourceRelationResource'
    Languages:
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          example:
            en-US: English
            fr-FR: French
            de-DE: German
    ErrorResponse:
      properties:
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 400
        message:
          type: string
  responses:
    TranslationsResponse:
      description: The list of translations
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Translations'
    TranslatableResponse:
      description: The list of translatable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Translatable'
    TranslatableStatusResponse:
      description: The list of translatable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TranslatableStatus'
    TranslateResponse:
      description: The resource is translated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Translated'
    ResourceRelationsResponse:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceRelations'
    LanguagesResponse:
      description: The list of languages
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Languages'
    BadRequestResponse:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerErrorResponse:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'